In [0]:
import numpy as np
from numpy.linalg import svd

In [0]:
A = np.array([[1,2,3],[2,3,4]])
A

In [0]:
U,S,VT = svd(A)

In [10]:
print(VT)

[[-0.33809817 -0.55064932 -0.76320047]
 [ 0.84795222  0.17354729 -0.50085764]
 [ 0.40824829 -0.81649658  0.40824829]]
